name: Run Service Tests

on:
  push:
    branches:
      - main
    paths:
      - services/**
      - .github/workflows/test.yaml 
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: filter 
        id: filter 
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          filters: .github/utils/file-filters.yaml

  tests:
    name: Execute Service Test Matrix
    runs-on: ubuntu-latest
    needs: filter

    strategy:
      fail-fast: false
      matrix:
        service:
          [
          "services/node/api-node",
          "services/react/client-react",
          "services/go/api-golang",
          "services/python/load-generator-python"

          ]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # Node.js setup (Node services only)
      # -------------------------------
      - name: Configure Node.js
        if: ${{ startsWith(matrix.service, 'services/node/' || startsWith(matrix.service, 'services/react/')) }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.service }}/package.json
          cache: npm
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      # -------------------------------
      # Go setup (Go services only)
      # -------------------------------
      - name: Configure Go
        if: ${{ startsWith(matrix.service, 'services/go/') }}
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum
      # -------------------------------
      # python setup (python services only)
      # -------------------------------
      - name: install poetry 
        if: ${{ startsWith(matrix.service, 'services/python/') }}
        uses:  snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a #v1.4.1
      - name: Configure python
        if: ${{ startsWith(matrix.service, 'services/python/') }}
        uses:  actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6.1.0
        with:
          python-version-file: ${{ matrix.service }}/pyproject.toml
          cache-dependency-path: ${{ matrix.service }}/poetry.lock

      # -------------------------------
      # Task runner
      # -------------------------------
      - name: Install Task runner
        uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/go-task/task/releases/download/v3.44.1/task_linux_amd64.tar.gz
          name: task
          version: v3.44.1

      # -------------------------------
      # Dependency installation
      # -------------------------------
      - name: Install project dependencies
        working-directory: ${{ matrix.service }}
        run: task install-ci

      # -------------------------------
      # Test execution
      # -------------------------------
      - name: Execute test suite
        working-directory: ${{ matrix.service }}
        run: task test
